@startuml
skinparam sequenceMessageAlign left
skinparam shadowing false
hide footbox
participant "Client App" as App
participant "FHIR Server" as Server

App -> Server : Discovery request
App <-- Server : Discovery response
@enduml