@startuml
skinparam sequenceMessageAlign left
skinparam shadowing false
hide footbox
participant "Client App" as App
participant "Authorization Server" as Server
App -> Server : Token request
App <-- Server : Token response
@enduml